### ISSUE TITLE
hvt: Free dynamically allocated memory

### ISSUE THREAD

**Issue by cmainas** [Solo5/solo5#484] opened 2020-11-19 09:46 UTC
Hello,

we were looking how the hvt tender handles the mft struct and we noticed that while this struct is dynamically allocated, there was no free for its memory. In that context we searched a bit more in the code and we found that the same happens with two more structures (cpuid and hvt). 

The cpuid struct is used only to set the cpuid in KVM while the other structs are used throughout the VM's lifecycle.
We understand that this is not that critical as long as the OS will free the heap at the end of hvt's execution, but a lot of people consider freeing the allocated memory as a good practice.

Let us know if you think it is a good idea. If yes, we can create a pull request based on this patch:
https://github.com/nubificus/solo5/commit/6fe1ca1780b024aa895ad6033d387a2e014bfd35

**Comment by mato** [comment] 2020-11-19 10:09
> We understand that this is not that critical as long as the OS will free the heap at the end of hvt's execution, but a lot of people consider freeing the allocated memory as a good practice.

Relying on the OS behaviour of cleaning up process resources on exit in `hvt` is deliberate. What specifically, other than "best practice", prompted you to investigate this?

> Let us know if you think it is a good idea. If yes, we can create a pull request based on this patch:

It's a good idea, but there are more things to consider:

If there is to be a "free" / "deinit" / "fini" (I prefer this last one, actually) function in the public hvt API, then it should clean up _all_ resources, i.e. close KVM fds, and so on. Also, this would need to be implemented for the other backends (FreeBSD, OpenBSD VMMs).

In other words, a user of that API should be able to call `hvt_fini()`, and then reinitialise things again from the beginning in the same process. Otherwise the function doesn't really make sense to me. However, again, besides "best practice", do you see an actual use case for this? Be aware that once you've loaded the guest into memory the process should be considered tainted, so you really don't want to go and do it again...

On a related note, with the `spt` tender an equivalent `spt_fini()` function is _not possible_ by design, since after jumping into the unikernel we're a) inside a strict seccomp sandbox, b) the unikernel never jumps back to the tender and always exits directly via the syscall. From a maintenance perspective, I prefer symmetry in the APIs and tenders where it makes sense.

**Comment by cmainas** [comment] 2020-11-19 14:21
> 
> Relying on the OS behaviour of cleaning up process resources on exit in `hvt` is deliberate. What specifically, other than "best practice", prompted you to investigate this?
> 

We were testing the new solo5 ABI (v0.6) on our WIP in kernel monitor and as long as we are inside the kernel we have to take care of any dynamically allocated memory. In that context we searched how hvt handles dynamically allocated memory. Also at first i thought it might be a memory leak but after some search we found out that it is not that critical.

> If there is to be a "free" / "deinit" / "fini" (I prefer this last one, actually) function in the public hvt API, then it should clean up _all_ resources, i.e. close KVM fds, and so on. Also, this would need to be implemented for the other backends (FreeBSD, OpenBSD VMMs).
> 
> In other words, a user of that API should be able to call `hvt_fini()`, and then reinitialise things again from the beginning in the same process. Otherwise the function doesn't really make sense to me. However, again, besides "best practice", do you see an actual use case for this? Be aware that once you've loaded the guest into memory the process should be considered tainted, so you really don't want to go and do it again...
> 

We did not have any use-case in mind when we searched about it. On the other hand, a possible use-case would be to reuse the already initialized vcpu(s) for a consecutive run of a different workload. In that scenario fini could work as a cleanup function between these executions. Of course this arises a lot of security concerns and discussion which i think it is out of scope for this issue. 

All in all i agree regarding mft and hvt but maybe cpuid could be freed.
https://github.com/nubificus/solo5/commit/6fe1ca1780b024aa895ad6033d387a2e014bfd35#diff-55e43d3cdfb711c3f470f79c0175e317f5722f2359c9d63cea7077f05539b580R61

**Comment by mato** [comment] 2020-11-19 15:59
> All in all i agree regarding mft and hvt but maybe cpuid could be freed.

Yes, that's a bug, done in #485, thanks for pointing it out.

**Comment by mato** [comment] 2020-12-17 12:56
I don't think there is anything else to action here at the moment, can we close this?

**Comment by cmainas** [comment] 2021-01-05 10:59
Yeah sure. Thank you for your time and discussion

**Closed** 2021-01-05 13:03 UTC
Labels: design, enhancement, target/hvt
