### ISSUE TITLE
Support OSv unikernel

### ISSUE THREAD

**Issue by wkozaczuk** [Solo5/solo5#249] opened 2018-03-28 12:02 UTC
I am one of the committers of [the OSv unikernel](https://github.com/cloudius-systems/osv). As you may know OSv is very universal is the sense that it supports running any unmodified or almost unmodified Linux apps. For example we can run unmodified Java, Node.js, Python and Golang apps. With recent addition of ROFS (Read Only file system) we can now boot OSv with C hello world app in around 120-150ms on QEMU/KVM once QEMU is up. But starting QEMU itself is pretty slow and overall QEMU + OSv takes around 1000ms to boot (based on what time says). So concluding I am very interested in speeding up the boot process by using uKVM monitor - I saw that uKVM can boot in a matter of 10-20 ms.

As I understand uKVM monitor can replace QEMU in KVM/QEMU combination. Right know OSv provides virtual device drivers to boot on QEMU/KVM, XEN, VMware hypervisors and VirtualBox. As I understand we would need to implement uKVM specific device drivers (console, time source, block and networking devices, etc). Also currently OSv expects CPU in 16-bit real mode when booting, probes PCI controller, etc as it is described [here](https://github.com/cloudius-systems/osv/wiki/OSv-early-boot-(MBR)). I think uKVM prepares CPU to be in 64-bit mode so on OSv side we would need to tweak this part of the boot process.

Anyhow I was wondering how difficult it would be to make OSv to boot/run on uKVM. As I indicated above on OSv side I think we would need to change the boot process and implement new device drivers. In first stage to prove it works we could start with drivers for console and timesource only (block and networking devices later). What would have to be done on uKVM side if any? Could you please point me to the code examples (any docs) of uKVM device drivers? Is there anything fundamental that prevents OSv from running on uKVM?

BTW we have a [tracking issue](https://github.com/cloudius-systems/osv/issues/886) for uKVM support so please feel free to comment there as well. Also I am adding @nyh as he may chime in with more details than me.

**Comment by ricarkol** [comment] 2018-03-29 01:41
Hi @wkozaczuk, this would be great! Let me share some relevant ukvm details, and what I think is the biggest challenge for supporting OSv.

- ukvm starts VMs on 64-bit mode with page tables and segment registers already set. Note that as much setup as possible is
  done before starting the VM. The philosophy is that the guest doesn't discover what devices it has. The devices
  are known at build time. So, there is no need to enumerate PCI devices or something like that. As an example, setup for x86_64 is here: https://github.com/Solo5/solo5/blob/master/ukvm/ukvm_hv_kvm_x86_64.c#L79.
- there is no PCI. There are plans to have some type of ring (PCI like), but at the moment we have a very
  simple hypercall mechanism for IO (https://github.com/Solo5/solo5/blob/master/ukvm/ukvm_guest.h#L63). For example, to perform block IO, the
  guest passes a buffer pointer with an `out` instruction, like this: https://github.com/Solo5/solo5/blob/master/kernel/ukvm/block.c#L63
- ukvm only uses trap handlers that just report errors and die (https://github.com/Solo5/solo5/blob/master/kernel/cpu_x86_64.c#L165). IO in solo5 doesn't use interrupts for IO or preemption.
- waiting for IO is done via `solo5_yield` which translates to a linux `ppoll` on the device FDs (like the FD for the network TAP), here: https://github.com/Solo5/solo5/blob/master/ukvm/ukvm_core.c#L121.

The solo5 interface which is what ukvm implements with hypercalls (https://github.com/Solo5/solo5/blob/master/kernel/solo5.h) is designed to run unikernels with cooperative schedulers. solo5/ukvm doesn't implement preemption, not even to handle arriving packets. All unikernels supported by solo5 implement an event loop like this one:

```
while (1)
	block until waketime or until an interrupt occurs
	handle timer (if one fired)
	handle packet (if one arrived)
```

which now have a solo5/ukvm version that looks like this:

```
while (1)
	solo5_yield(timer_sleep_time) --> ppoll(TAP_fd, timer_sleep_time)
	handle timer (if one fired)
	handle packet (if one arrived) --> solo5_read(buf)
```

As an example, the MirageOS event loop implemented using the solo5 interface is here: https://github.com/mirage/mirage-solo5/blob/master/lib/main.ml#L59
The includeos is here: https://github.com/hioa-cs/IncludeOS/blob/master/src/platform/x86_solo5/os.cpp#L142, and the
rumprun one is here (just a prototype): https://github.com/ricarkol/rumprun/blob/solo5/lib/libbmk_core/sched.c#L355.

If the OSv scheduler can be fit into something like the above event loop, then things should be straightforward.

**Comment by wkozaczuk** [comment] 2018-03-29 22:47
Hi @ricarkol, 

Thanks for your reply. Everything seems to be doable except the scheduler part which might be a show stopper. From what I understand OSv implements preemptive, tick-less scheduler that runs an idle thread (aka event loop) on each vCPU and selects new thread to run from local runqueue associated with this vCPU. New thread is given a time slice to run so OSv needs a mechanism (I think an interrupt) to know time has expired so it can schedule another thread. For details look here - https://github.com/cloudius-systems/osv/blob/master/core/sched.cc#L411. 

So I guess one option would be to create ukvm version of OSv scheduler that would be cooperative but I am not sure how difficult or even feasible it is. Second option would be to have "ukvm event loop" threads in OSv to handle IO (block and net) that would follow logic outlined by your pseudo-code (2nd one) and maybe bypass kernel/ukvm/* layer and use hypercall mechanism directly. Not sure if that it feasible.

If you have any other ideas please let know.

**Comment by wkozaczuk** [comment] 2018-04-02 15:53
So to rephrase the second option: would it be possible to leverage uKVM to bootstrap vCPUs and other KVM resources and then have OSv take over and orchestrate interactions with virtual devices from OSv controlled "event loop" threads while utilizing solo5/ukvm API?

**Comment by ricarkol** [comment] 2018-04-02 16:25
Hi @wkozaczuk , the issue with option 2 is that bypassing the solo5 interface (having OSv take over) would lead to a lot of maintenance pain and would only work for ukvm-bin (and only this one version). Solo5 can run on multiple platforms like the muen separtion kernel, regular qemu, ukvm-bin, as a process on a limited set of seccomp syscalls (prototype), and potentially SGX (there is people working on SGX support). Ideally, we would want OSv to run on all of those.

I'm leaning towards option 1. The issue there is whether apps, and OSv kernel threads (specially these) can be happy without preemption. Actually, that would be the first experiment to try: ignore ukvm-bin and solo5, make the OSv scheduler non-preemptive, and see what happens. Based on the OSv paper: "A thread can temporarily avoid being preempted by incrementing a per-thread preempt-disable counter.". What do you think?

**Comment by mato** [comment] 2018-04-04 10:13
@wkozaczuk To add to this, without going into too much implementation detail:

The guest-facing API you should be porting against is the Solo5 API defined in `kernel/solo5.h`. As Ricardo notes, the ukvm hypercall API is technically an "internal implementation detail" in the grand scheme of things, so you would lose out on other (non-hardware-virtuatization) targets supported by Solo5. Sorry that this is not really codified anywhere, we're working on better documentation.

As for what to do about the OSv scheduler, I don't think separate threads are a viable solution since Solo5 (and thus ukvm) does not have any preemption mechanism (or VCPU interrupts!) by design, therefore you'd have no way of scheduling those threads in a preemptive design.

**Comment by wkozaczuk** [comment] 2018-04-08 01:36
Thanks for the information. I need to digest it a little bit more and run
it by people that know more about OSv internals more than I do. But my gut
feeling tells me that making OSv run on uKVM seems to be more daunting task
than I thought.

**Comment by mato** [comment] 2018-04-19 10:48
@wkozaczuk We have now set up a [mailing list](https://github.com/Solo5/solo5#contributing-and-community) for general Solo5 development discussion. I'm going to close this issue, since it's precisely the kind of discussion that the list is intended for (as opposed to a concrete bug or task, which stay in Github issues). Feel free to subscribe and continue the discussion there when ready.

**Closed by mato** 2018-04-19 10:48 UTC
