### ISSUE TITLE
New maintainer needed

### ISSUE THREAD

**Issue by mato** [Solo5/solo5#498] opened 2021-11-11 13:20 UTC
Effective today, I am stepping down from maintaining Solo5 and from the core team of MirageOS.

What does that mean?

I will no longer monitor pull requests or issues filed on repositories in the Solo5/ organisation on GitHub, with the exception of this
issue of appointing a new maintainer for Solo5.

Given that MirageOS is the primary downstream of Solo5, I would prefer that members of the MirageOS community step up to continue maintenance of Solo5. Failing that, perhaps there is someone in the wider community who is interested.

For details please see the full e-mail at https://www.mail-archive.com/solo5@lists.h3q.com/msg00097.html.

**Comment by avsm** [comment] 2021-11-24 15:53
Firstly, of course, many thanks to Martin for the wonderful maintainership to date.

Moving forwards, I can confirm that I have admin access to the solo5 org, and there is a meeting of the MirageOS core team on the 25th Nov 2021 (tomorrow) in order to find out who has time and interest to step up.

**Comment by dinosaure** [comment] 2021-11-30 12:28
Hi,

We did the meeting with the @mirage/core team and we agreed that @TheLortex and me will maintain & release Solo5. @avsm, @djs55 and @hannesm will keep their eyes on the project to keep the quality of this project made by the Solo5 core team.

From our perspective, #494 will be merged and Solo5.0.8.0 will be released. This is our initial plan with Martin about the release of MirageOS 4. So we will achieve that as soon as possible :+1:. About technical details (I know that NixOS is aware about that), we will **not** support a retro-compatibility with MirageOS 3. By this way, we can merge #494 without any changes and definitely delete `pkg-config` from our workflow.

Then, in the way of MirageOS 4, we will continue to maintain and improve Solo5 and we will try to answer the existing issues. In our mind, OpenBSD support (see #495), NixOS support (see #496) and SCSI support. This is our court/middle term goals about Solo5.

I would like to thanks Martin for all of his job on this great project. It help us a lot to provide _unikernels_ and we will continue to improve it to obtain a better experience about virtualization/deployment of _unikernels_.

**Comment by hannesm** [comment] 2021-12-01 13:13
First of all, thanks @mato for your impressive work on solo5 (and various other parts of the MiageOS ecosystem) - a system developed in C without much `ifdef`, very stable across platforms and compilers, nearly bug free (the only one I remember is #460).

Then - about the plan - thanks to @dinosaure and @TheLortex for taking on. My concern with the above plan is the lack of mention of a CI -- I really appreciate the huge matrix of e2e tests and platforms they are executed on. I personally think that such a huge automated coverage is crucial for further development and maintenance of solo5 (before planning releases) - to avoid bitrot and bad changes on some code paths (OpenBSD vmm, the xen code, ...).

**Comment by avsm** [comment] 2021-12-13 09:28
Many thanks for volunteering, @dinosaure @TheLortex!  I'll add you both as maintainers now. If you could ensure that the CHANGES file and README remains uptodate I'd appreciate it.

**Closed by avsm** 2021-12-13 09:28 UTC

**Comment by hannesm** [comment] 2025-10-22 07:42
Since @TheLortex has moved on, I'm happy to volunteer doing some maintenance work (triaging, setup a GitHub CI, ...) if I get the necessary permissions.
