### ISSUE TITLE
tsc time source broken on bhyve

### ISSUE THREAD

**Issue by hannesm** [Solo5/solo5#144] opened 2016-12-10 21:12 UTC
I get some monotonic time in the right interval, but it is not gettimeofday (`2016-12-12T21:52:17-00:00` in VM vs `Sat 10 Dec 2016 22:09:30 CET` on host).

`kernel/virtio/tscclock.c` is in use.

while investigating, I found that the code getting the time still uses the OCaml runtime and its float conversion, we should use a timeval in mirage-clock-freestanding and get rid of the floating point conversions.

**Comment by mato** [comment] 2016-12-12 13:57
I can reproduce this on `bhyve`, but not on software-only `qemu` (which uses the same TSC clock code as bhyve). Will investigate some more and see what I can find, my guess is we might be tickling something in bhyve's RTC emulation which is giving us wrong values for wall time.

`mirage-clock-freestanding` using float conversions is a separate issue, should be reported there.

**Comment by mato** [comment] 2016-12-12 15:23
I've found what looks like the root cause of the problem. The `tscclock` RTC code is correct, however on KVM and QEMU (irrespective of whether or not the RTC is involved) the TSC begins counting at zero when the VM is initialised. On Bhyve the TSC appears to be either passed through directly from the host or otherwise initialised to an unspecified base value.

The Solo5 clock code uses the TSC base value as the base for monotonic time (see https://github.com/Solo5/solo5/blob/master/kernel/virtio/tscclock.c#L203 for the `tscclock` case) and assumes that this starts at zero at boot time. The wall clock value value is only read _once_, then used as an offset against monotonic time. Unfortunately this assumption is violated in the bhyve case so the wall clock TOD is incorrect.

**Comment by mato** [comment] 2016-12-13 19:50
Fixed in #146.

**Closed by mato** 2016-12-13 19:50 UTC
