### ISSUE TITLE
[Debian 9.x] build fails with test_fpu.genode: error: PHDR segment not covered by LOAD segment

### ISSUE THREAD

**Issue by nikhedonia** [Solo5/solo5#444] opened 2020-03-28 12:50 UTC
Hi solo5 team.
I'd wanted to take solo5 for a testdrive but unfortunately the build fails with the error message above.
Here the complete output:

```
➜  solo5 git:(master) ✗ PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig SURF_BUILD_TYPE=basic ./build.sh
********************************************************************************
System information:
********************************************************************************
Linux LoopPerfect 5.4.0-4-amd64 #1 SMP Debian 5.4.19-1 (2020-02-13) x86_64 GNU/Linux
Compiler (cc) version:
cc (Debian 9.2.1-30) 9.2.1 20200224
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compiler version detail:
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 9.2.1-30' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-mutex
Thread model: posix
gcc version 9.2.1 20200224 (Debian 9.2.1-30) 
Linker (ld) version:
GNU ld (GNU Binutils for Debian) 2.34
********************************************************************************
Starting build.
********************************************************************************
configure.sh: Configured for x86_64-linux-gnu.
configure.sh: Enabled targets: hvt spt virtio muen genode.
GEN include/solo5/solo5_version.h
MAKE bindings
MAKE tenders
MAKE elftool
MAKE tests
MAKE test_seccomp
MAKE test_fpu
LD test_fpu.genode
ld: test_fpu.genode: error: PHDR segment not covered by LOAD segment
make[2]: *** [../Makefile.tests:73: test_fpu.genode] Error 1
make[1]: *** [GNUmakefile:33: test_fpu] Error 2
make: *** [GNUmakefile:70: tests] Error 2
FAILURE: 'make' failed: Status: 2
```

Any advise how to resolve this issue?

**Comment by mato** [comment] 2020-03-29 14:41
Hi @nikhedonia. Why are you trying to "emulate" the surf-build process? This is only intended for use by CI.

If you follow the [documented](https://github.com/Solo5/solo5/blob/master/docs/building.md) build instructions (i.e. `./configure.sh && make'), do you still hit this problem?

**Comment by nikhedonia** [comment] 2020-03-29 22:37
Thanks for the quick reply.

> Why are you trying to "emulate" the surf-build process? 
I'm not trying this intentionally; running `./configure.sh && make` yields the same error:

```
➜  solo5 git:(master) ✗ PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig SURF_BUILD_TYPE=basic ./configure.sh && make
configure.sh: Configured for x86_64-linux-gnu.
configure.sh: Enabled targets: hvt spt virtio muen genode.
GEN include/solo5/solo5_version.h
MAKE bindings
MAKE tenders
MAKE elftool
MAKE tests
MAKE test_seccomp
MAKE test_fpu
LD test_fpu.genode
ld: test_fpu.genode: error: PHDR segment not covered by LOAD segment
make[2]: *** [../Makefile.tests:73: test_fpu.genode] Error 1
make[1]: *** [GNUmakefile:33: test_fpu] Error 2
```

**Comment by mato** [comment] 2020-03-30 09:33
Ah, I see you're on Debian 9. This is no longer in CI, and thus not really supported any more.

I presume you don't need the Genode build? You can disable it by editing `Makeconf` after running `configure.sh`, and set `CONFIG_GENODE=` (i.e. blank). Everything else should work fine.

**Comment by mato** [comment] 2020-03-30 14:19
Actually, this is a duplicate of #441. Closing this, and will ping the Genode maintainers there.

**Closed by mato** 2020-03-30 14:19 UTC
Labels: host/linux, target/genode
